# ドラマ vectorization and recommender

Import packages

In [1]:
import pandas as pd
import ast

pd.set_option('display.max_columns', 200)
pd.set_option('display.max_colwidth', 200)

# Import Data

In [2]:
df_raw = pd.read_pickle('df_wiki.pkl')

Data Preprocessing Area

In [3]:
df = df_raw.copy()

df['hour'] = df.time.apply(lambda x: x[0]).str.extract(r'^([0-9]+)時')
df['time_start'] = pd.to_datetime(df.time.apply(lambda x: x[0]), format= '%H時%M分', errors='coerce')
df['time_end'] = pd.to_datetime(df.time.apply(lambda x: x[1] if len(x) > 1 else None), format= '|%H時%M分', errors='coerce')
df['min_length'] = (df['time_end'] - df['time_start']).astype('timedelta64[m]')

# Make up after calculation
df['time_start'] = df['time_start'].dt.time
df['time_end'] = df['time_end'].dt.time

df = df.drop(['date', 'time', 'url_wiki_zh', 'url', 'theme_song'], axis=1)

In [4]:
df.query('name_ja == "失恋ショコラティエ"')

,weekday,name_zh,name_ja,url_wiki_ja,TV,char_main,char_others,year,season,ジャンル,原作,脚本,監督,出演者,オープニング,エンディング,プロデューサー,制作,放送チャンネル,音声形式,放送国・地域,放送時間,放送期間,放送分,回数,演出,放送枠,ナレーター,製作総指揮,映像形式,企画,原案,シーズン数,製作,音楽,時代設定,チーフ・,作,制作統括,声の出演,言語,放送局,プロデュース,国・地域,話数,撮影地,撮影監督,編集,別名,シリーズ数,監修,配信サイト,配信期間,続編,配信国・地域,配信時間,各話の長さ,前作,制作プロデューサー,関連番組,エグゼクティブ・,テーマ曲作者,作曲,総監督,ディレクター,構成,hour,time_start,time_end,min_length
1,一,失戀巧克力職人,失恋ショコラティエ,https://ja.wikipedia.org/wiki/%E5%A4%B1%E6%81%8B%E3%82%B7%E3%83%A7%E3%82%B3%E3%83%A9%E3%83%86%E3%82%A3%E3%82%A8,[CX],[松本潤],"[石原聰美, 溝端淳平, 水川麻美, 佐藤隆太, 有村架純, 加藤成亮, 水原希子, 眞島秀和, 竹中直人]",2014,1,[テレビドラマ],[水城せとな],"[安達奈緒子, 越川美埜子]",NaN,"[松本潤, 石原さとみ, 水川あさみ, 水原希子, 溝端淳平, 有村架純, 佐藤隆太, 竹中直人, 加藤シゲアキ, 眞島秀和, 夏月, 佐藤祐基, 若月佑美, 千葉雄大]",[Ken Arai「Marble」],[嵐「Bittersweet」],"[若松央樹, 小原一隆]",[フジテレビ],NaN,NaN,[日本],[月曜日21:00 - 21:54],[2014年1月13日-3月24日],[54分],[11],"[松山博昭, 宮木正悟, 関野宗紀, 品田俊介, 小原一隆]",[フジテレビ月曜9時枠の連続ドラマ],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21,21:00:00,21:54:00,54.0

In [5]:
df.loc[df.ジャンル.isnull()][['name_ja', 'year', 'season', 'hour', 'min_length', 'TV', '出演者', 'url_wiki_ja']]

,name_ja,year,season,hour,min_length,TV,出演者,url_wiki_ja
5,紙の月,2014,1,22,48.0,[NHK],NaN,https://ja.wikipedia.org/wiki/%E3%83%86%E3%83%AC%E3%83%93%E3%83%89%E3%83%A9%E3%83%9E
8,今夜は心だけ抱いて,2014,1,23,29.0,"[田中美佐子, 土屋太鳳]",NaN,https://ja.wikipedia.org/wiki/%E4%BB%8A%E5%A4%9C%E3%81%AF%E5%BF%83%E3%81%A0%E3%81%91%E6%8A%B1%E3%81%84%E3%81%A6
14,テレビ東京開局50周年特別企画新春ワイド時代劇 影武者徳川家康,2014,1,18,300.0,[TX],NaN,https://ja.wikipedia.org/wiki/%E6%96%B0%E6%98%A5%E3%83%AF%E3%82%A4%E3%83%89%E6%99%82%E4%BB%A3%E5%8A%87
15,科捜研の女Season13,2014,1,19,56.0,[EX],NaN,https://ja.wikipedia.org/wiki/%E6%A8%8B%E5%8F%A3%E9%9A%86%E5%89%87
20,慰謝料弁護士〜あなたの涙、お金に変えましょう〜,2014,1,23,NaN,[YTV],"[田中直樹, 矢田亜希子, 渡辺直美, 山田菜々, 岩﨑名美, 高嶋香帆, 美保純]",https://ja.wikipedia.org/wiki/%E6%85%B0%E8%AC%9D%E6%96%99%E5%BC%81%E8%AD%B7%E5%A3%AB%E3%80%9C%E3%81%82%E3%81%AA%E3%81%9F%E3%81%AE%E6%B6%99%E3%80%81%E3%81%8A%E9%87%91%E3%81%AB%E5%A4%89%E3%81%88%E3%...
...,...,...,...,...,...,...,...,...
1165,きれいのくに,2021,2,20,43.0,[NHK],"[吉田羊, 蓮佛美沙子, 平原テツ, 小野花梨, 橋本淳, 加藤ローサ, 青木柚, 見上愛, 岡本夏美, 山脇辰哉, 秋元龍太朗, 稲垣吾郎]",https://ja.wikipedia.org/wiki/%E3%81%8D%E3%82%8C%E3%81%84%E3%81%AE%E3%81%8F%E3%81%AB
1170,著飾る戀には理由があって,2021,2,22,57.0,[TBS],NaN,https://ja.wikipedia.org/wiki/%E7%99%BE%E4%BA%BA%E4%B8%80%E9%A6%96
1184,70才、初めて産みますセブンティウイザン。,2021,2,22,43.0,[NHK],"[小日向文世, 竹下景子, 伊藤歩, 矢本悠馬, 臼田あさ美, 蔵下穂波, 田中美央, 笑福亭鶴光, 山本圭祐, 竜雷太, ふせえり, 前田亜季, 吉澤健, 根岸季衣, 宇崎竜童, 中村梅雀]",https://ja.wikipedia.org/wiki/%E3%82%BB%E3%83%96%E3%83%B3%E3%83%86%E3%82%A3%E3%82%A6%E3%82%A4%E3%82%B6%E3%83%B3
1193,泣くな研修醫,2021,2,23,30.0,[EX],NaN,
1196,リカ〜リバース〜,2021,2,23,-1385.0,[THK],NaN,https://ja.wikipedia.org/wiki/%E3%83%86%E3%82%A4%E3%83%AB%E3%82%BA%20%E3%82%AA%E3%83%96%20%E3%83%AA%E3%83%90%E3%83%BC%E3%82%B9

In [6]:
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1206 entries, 0 to 1205
Data columns (total 70 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   weekday      1206 non-null   object
 1   name_zh      1206 non-null   object
 2   name_ja      1206 non-null   object
 3   url_wiki_ja  1206 non-null   object
 4   TV           1206 non-null   object
 5   char_main    1206 non-null   object
 6   char_others  1206 non-null   object
 7   year         1206 non-null   int64
 8   season       1206 non-null   int64
 9   ジャンル         1017 non-null   object
 10  原作           545 non-null    object
 11  脚本           961 non-null    object
 12  監督           364 non-null    object
 13  出演者          1025 non-null   object
 14  オープニング       305 non-null    object
 15  エンディング       600 non-null    object
 16  プロデューサー      819 non-null    object
 17  制作           841 non-null    object
 18  放送チャンネル      290 non-null    object
 19  音声形式         642 non-null    object
 20  放送国・地域       1023 non-null   object
 21  放送時間         1019 non-null   object
 22  放送期間         1027 non-null   object
 23  放送分          987 non-null    object
 24  回数           984 non-null    object
 25  演出           645 non-null    object
 26  放送枠          935 non-null    object
 27  ナレーター        198 non-null    object
 28  製作総指揮        184 non-null    object
 29  映像形式         245 non-null    object
 30  企画           151 non-null    object
 31  原案           23 non-null     object
 32  シーズン数        25 non-null     object
 33  製作           398 non-null    object
 34  音楽           333 non-null    object
 35  時代設定         151 non-null    object
 36  チーフ・         125 non-null    object
 37  作            34 non-null     object
 38  制作統括         80 non-null     object
 39  声の出演         16 non-null     object
 40  言語           281 non-null    object
 41  放送局          32 non-null     object
 42  プロデュース       37 non-null     object
 43  国・地域         266 non-null    object
 44  話数           33 non-null     object
 45  撮影地          17 non-null     object
 46  撮影監督         16 non-null     object
 47  編集           32 non-null     object
 48  別名           44 non-null     object
 49  シリーズ数        39 non-null     object
 50  監修           76 non-null     object
 51  配信サイト        35 non-null     object
 52  配信期間         37 non-null     object
 53  続編           4 non-null      object
 54  配信国・地域       27 non-null     object
 55  配信時間         5 non-null      object
 56  各話の長さ        20 non-null     object
 57  前作           4 non-null      object
 58  制作プロデューサー    1 non-null      object
 59  関連番組         6 non-null      object
 60  エグゼクティブ・     6 non-null      object
 61  テーマ曲作者       2 non-null      object
 62  作曲           2 non-null      object
 63  総監督          3 non-null      object
 64  ディレクター       1 non-null      object
 65  構成           1 non-null      object
 66  hour         1196 non-null   object
 67  time_start   1192 non-null   object
 68  time_end     1040 non-null   object
 69  min_length   1040 non-null   float64
dtypes: float64(1), int64(2), object(67)
memory usage: 659.7+ KB

In [7]:
for col in df.columns:
    print(f"{col} value counts = {df[col].value_counts()}")

weekday value counts = 六       241
日       227
四       171
五       165
三       129
二       125
一        58
一至五      27
一至六      25
六至日      13
          4
三至四       3
一至四       2
日至一       2
三至日       2
五至六       2
二至六       2
一至二       1
二至四       1
日四        1
二至五       1
一至日       1
四至五       1
一至三       1
六三至四      1
Name: weekday, dtype: int64
name_zh value counts = 烈車戰隊特急者                              5
麒麟來了                                 4
直衝青天                                 4
真田丸                                  4
花燃燒                                  4
                                    ..
女科调员Season13                         1
是生是死還是父親（日语：生きるとか死ぬとか父親とか#テレビドラマ）    1
打耳光！～律師事務員箕輪用愛解決一切～                  1
半澤直樹2                                1
時間巡邏的OL                              1
Name: name_zh, Length: 1125, dtype: int64
name_ja value counts = 烈車戦隊トッキュウジャー           5
いだてん〜東京オリムピック噺〜        4
科捜研の女 第19シリーズ          4
真田丸                    4
青天を衝け                  4
                      ..
今ここにある危機とぼくの好感度について    1
ファースト・クラス              1
探偵☆星鴨                  1
科捜研の女 第14シリーズ          1
わにとかげぎす                1
Name: name_ja, Length: 1120, dtype: int64
url_wiki_ja value counts = https://ja.wikipedia.org/wiki/%E3%83%86%E3%83%AC%E3%83%93%E3%83%89%E3%83%A9%E3%83%9E                                                                            15
https://ja.wikipedia.org/wiki/%E7%9B%B8%E6%A3%92                                                                                                                14
https://ja.wikipedia.org/wiki/%E7%A7%91%E6%8D%9C%E7%A0%94%E3%81%AE%E5%A5%B3                                                                                     13
                                                                                                                                                                12
https://ja.wikipedia.org/wiki/%E3%82%84%E3%81%99%E3%82%89%E3%81%8E%E3%81%AE%E5%88%BB%E3%80%9C%E9%81%93                                                           6
                                                                                                                                                                ..
https://ja.wikipedia.org/wiki/%E3%83%88%E3%83%89%E3%83%A1%E3%81%AE%E6%8E%A5%E5%90%BB                                                                             1
https://ja.wikipedia.org/wiki/%E7%A0%82%E3%81%AE%E5%A1%94%E3%80%9C%E7%9F%A5%E3%82%8A%E3%81%99%E3%81%8E%E3%81%9F%E9%9A%A3%E4%BA%BA                                1
https://ja.wikipedia.org/wiki/%E3%83%AC%E3%83%83%E3%83%89%E3%82%AF%E3%83%AD%E3%82%B9%E3%80%9C%E5%A5%B3%E3%81%9F%E3%81%A1%E3%81%AE%E8%B5%A4%E7%B4%99%E3%80%9C     1
https://ja.wikipedia.org/wiki/%E3%83%80%E3%83%BC%E3%82%AF%E3%82%B9%E3%83%BC%E3%83%84                                                                             1
https://ja.wikipedia.org/wiki/%E3%82%B5%E3%82%A4%E3%83%AC%E3%83%B3%E3%83%88%E3%83%BB%E3%83%97%E3%82%A2                                                           1
Name: url_wiki_ja, Length: 972, dtype: int64
TV value counts = [EX]             173
[NHK]            167
[CX]             161
[TX]             153
[TBS]            153
[NTV]            126
[[1]]             59
[[2]]             45
[[3]]             44
[KTV]             35
[YTV]             31
[[4]]             20
[THK]             16
[相武紗季]             1
[田中美佐子, 土屋太鳳]      1
[小松菜奈, 菊地凛子]       1
[仲里依紗]             1
[高良健吾]             1
[松雪泰子]             1
[MBS]              1
[神木隆之介]            1
[中山美穗]             1
[永山絢斗]             1
[黑木美沙]             1
[伊藤英明]             1
[及川光博, 黑木美沙]       1
[]                 1
[小出惠介]             1
[內村光良]             1
[木村文乃]             1
[佐佐木藏之介]           1
[玉山鐵二]             1
[大泉洋]              1
[市川染五郎]            1
[吉岡秀隆]             1
[本假屋唯香]            1
Name: TV, dtype: int64
char_main value counts = []               22
[澤口靖子]           16
[水谷豐]            14
[波瑠]             11
[上川隆也]            9
                 ..
[齋藤飛鳥]            1
[村上淳]             1
[有岡大貴]            1
[武田玲奈, 飯豐萬理江]     1
[鈴木浩介]            1
Name: char_main, Length: 583, dtype: int64
char_others value counts = []                                                            71
[網頁]                                                          19
[平牧仁, 梨里杏, 横濱流星, 森高愛, 長濱慎, 關根勤]                                5
[內藤剛志, 若村麻由美, 風間徹, 金田明夫, 齊藤曉, 渡部秀, 山本輝, 西田健, 石井一彰]             5
[內田理央, 吉井怜, 濱野謙太, 井俣太良, 瀧口幸廣, 上遠野太洸, 蕨野友也, 松島庄汰, 片岡鶴太郎]        5
                                                              ..
[羽田美智子, 津田寬治, 吹越滿, 田口浩正, 宮近海斗, 伊東四朗, 寺尾聰, 山田裕貴, 里見浩太朗]         1
[夏木麻里]                                                         1
[吉岡里帆, 真榮田郷敦, 岩田琉聖, 小西櫻子, 白石隼也, 松大航也奧平大兼, 木南晴夏, 片岡愛之助]         1
[笨蛋節奏, 豐本明長, 飯塚悟志, 角田晃廣, 早見朱莉]                                 1
[和久井映見, 桜田ひより, 二宮慶多, 伊藤和枝, 六角精兒, 宮川一朗太, 中島ひろ子, 谷井一郎, 岩本多代]     1
Name: char_others, Length: 1046, dtype: int64
year value counts = 2017    197
2014    192
2015    177
2016    175
2018    167
2019    129
2020     98
2021     71
Name: year, dtype: int64
season value counts = 1    369
2    320
4    272
3    245
Name: season, dtype: int64
ジャンル value counts = [テレビドラマ]              654
[連続ドラマ]               123
[刑事ドラマ]                62
[時代劇]                  34
[特撮テレビドラマ]             14
                     ...
[テレビドラマ, サスペンスホラー]      1
[コメディ、ロマンス[18]]         1
[恋愛ミステリードラマ]            1
[コメディーミステリー]            1
[帯番組/情報・バラエティ番組]        1
Name: ジャンル, Length: 77, dtype: int64
原作 value counts = [秋元康]                     9
[八手三郎]                    8
[久住昌之『孤独のグルメ』]            6
[富樫倫太郎, 『生活安全課0係』シリーズ]    5
[林真理子『西郷どん!』]             4
                         ..
[高瀬志帆]                    1
[杉森久英]                    1
[乾くるみ]                    1
[八月美咲]                    1
[辻堂魁]                     1
Name: 原作, Length: 443, dtype: int64
脚本 value counts = [輿水泰弘他]                                                                                             14
[岡田惠和]                                                                                              13
[スタッフ参照]                                                                                            13
[前川洋一]                                                                                               9
[黒岩勉]                                                                                                9
                                                                                                    ..
[竹山洋]                                                                                                1
[ソ・ヒョンギョン]                                                                                           1
[喜安浩平, 山田能龍, 真壁幸紀, 室岡ヨシミコ]                                                                           1
[田辺茂範（劇団 ロリータ男爵）, 矢島弘一（劇団 東京マハロ）, 角田貴志（劇団ヨーロッパ企画）, 山田由梨（劇団 贅沢貧乏）, 安藤奎（劇団 アンパサンド）, 玉田真也（劇団 玉田企画）]     1
[井上由美子（作）]                                                                                           1
Name: 脚本, Length: 551, dtype: int64
監督 value counts = [和泉聖治, 橋本一他]                  14
[スタッフ参照]                      13
[中澤祥次郎他]                       7
[倉貫健二郎, 竹村謙太郎, 岡野宏信]           5
[溝口憲司ほか]                       5
                              ..
[黒沢直輔, 石川一郎, 猪原達三（第2シーズン）]     1
[内田英治]                         1
[小林勇貴, 小路紘史, 西村喜廣]             1
[松本佳奈, 久万真路, 桑島憲司]             1
[内藤瑛亮]                         1
Name: 監督, Length: 263, dtype: int64
出演者 value counts = [篠原ゆき子（S19-1 - ）]                                                                                                                                                                14
[沢口靖子, 若村麻由美（S8. - ）, 斉藤暁（S1,S5. - ）, 渡部秀（SP9 - ）, 山本ひかる（S13.3 - ）, 石井一彰（S15. - ）, 風間トオル（SP3 - ）, 西田健（S12. - ）, 金田明夫（S13. - ）, 内藤剛志（S2. - S4,S5 - ）]                             13
[石坂浩二, 清野菜名, 風吹ジュン, 風間俊介, 橋爪功, 岸本加世子, 宮田俊哉, 平山浩行, 浅丘ルリ子, いしだあゆみ, 板谷由夏, 伊吹吾郎, 大空眞弓, 丘みつ子, 加賀まりこ, 上條恒彦, 草刈民代, 倉田保昭, 笹野高史, ジェリー藤尾, 名高達男, 藤竜也, 松原智恵子, 水野久美, ミッキー・カーチス, 山本圭, 八千草薫]     6
[志尊淳, 平牧仁, 梨里杏, 横浜流星, 森高愛, 長濱慎, 関根勤, 大口兼悟他]                                                                                                                                       5
[石田明（NON STYLE）, 中山美穂]                                                                                                                                                            5
                                                                                                                                                                                 ..
[神木隆之介, 田辺誠一, 岸井ゆきの, 佐藤隆太, 濱田マリ, 菅原大吉, 小堺一機, 南果歩]                                                                                                                                 1
[柄本佑, 小島瑠璃子, えなりかずき, 藤真利子]                                                                                                                                                        1
[藤原紀香]                                                                                                                                                                            1
[綾部祐二, 白石美帆]                                                                                                                                                                      1
[松田凌, 宮崎秋人, 安西慎太郎ほか]                                                                                                                                                              1
Name: 出演者, Length: 831, dtype: int64
オープニング value counts = [作曲：池頼広（S1 - ）]                      14
[氷室京介「OUTSIDE BEAUTY」]               13
[中島みゆき]                               6
[「孤独の咆哮」]                             5
[「烈車戦隊トッキュウジャー」[1], 歌：伊勢大貴]           5
                                     ..
[鴨宮諒「PANIC」]                          1
[ザ・ブロードサイド・フォー「若者たち」]                 1
[Hey! Say! JUMP「I am 」]               1
[Anly「EMERGENCY」]                     1
[Thinking Dogs, 『Heavenly ideas』]     1
Name: オープニング, Length: 217, dtype: int64
エンディング value counts = [ZARD「promised you」]                     14
[柴田淳「車窓」]                                13
[同上]                                     12
[「ビュンビュン!トッキュウジャー」[1], 歌：Project.R]       5
[伝美「五郎の12PM」]                             5
                                         ..
[歴代エンディングテーマを参照]                          1
[Superfly「Beautiful」]                     1
[円神, 「Say Your Name」]                     1
[クリス・ハート「あなたへ」]                           1
[Beverly, 「Baby don’t cry 〜神様に触れる唇〜」]     1
Name: エンディング, Length: 487, dtype: int64
プロデューサー value counts = [高野渉（S16 - ）]                    14
[スタッフ参照]                         13
[堀之内礼二郎]                          6
[小林宙]                             6
[櫨山裕子, 秋元孝之]                      5
                                 ..
[河西秀幸, 国本雅広, 髙橋史典]                1
[植野浩之、毛利忍]                        1
[瀬戸口克陽, 東仲恵吾, 植田春菜（協力P）]          1
[小松幸敏（テレビ東京）, 高石明彦（The icon）]     1
[井圡隆（GP）, 杉山登, 丸山真哉]              1
Name: プロデューサー, Length: 611, dtype: int64
制作 value counts = [テレビ朝日]                    98
[フジテレビ]                    76
[日本テレビ]                    59
[NHK]                      49
[テレビ東京]                    44
                           ..
[フジクリエイティブコーポレーション（協力）]     1
[テレビ東京, 楽映舎]                1
[Pipeline]                  1
[テレビ東京, ドリマックス・テレビジョン]      1
[東宝]                        1
Name: 制作, Length: 187, dtype: int64
放送チャンネル value counts = [テレビ東京系]                                      50
[NHK総合]                                       45
[NHK BSプレミアム]                                 28
[日本テレビ系]                                      25
[WOWOWプライム]                                   21
[テレビ朝日系]                                      20
[フジテレビ系]                                      18
[日本テレビ系列]                                     17
[TBS系]                                        14
[フジテレビ系列]                                      9
[TBS系列]                                        5
[日本放送協会]                                       4
[NHK BSプレミアム, NHK BS4K]                        3
[テレビ東京系列]                                      3
[NHK総合, NHK BS4K]                              3
[BSテレビ東京]                                      2
[JNN系]                                         2
[BSプレミアム]                                      2
[テレビ東京]                                        2
[カナダスペース, アメリカ合衆国BBCアメリカ]                      2
[ABEMA SPECIALチャンネル]                           1
[PTS]                                          1
[WOWOW]                                        1
[MBSテレビ他]                                      1
[NHK Eテレ]                                      1
[毎日放送（MBS）]                                    1
[フジテレビ]                                        1
[Hulu]                                         1
[NHK BS8K]                                     1
[フジテレビTWO]                                     1
[BSテレビ東京, テレビ大阪]                               1
[NHK総合テレビジョン]                                  1
[韓国MBC]                                        1
[tvN]                                          1
[アメリカ合衆国CBS, 日本NHK, 日本女性チャンネル♪LaLa TV, ほか]     1
Name: 放送チャンネル, dtype: int64
音声形式 value counts = [ステレオ放送]                                        487
[解説放送]                                           49
[ステレオ2音声, 副音声による解説放送]                            38
[ステレオ解説放送（S17-1〜）]                               14
[ステレオ解説放送（S18. - ）]                              13
[ダブルステレオ放送]                                       4
[ステレオ]                                            3
[ステレオ音声]                                          3
[ステレオ放送, 副音声放送（第4話・第7話 - 第9話）[注 1]]               2
[ステレオ放送（解説放送）]                                    2
[文字多重放送]                                          2
[解説放送(副音声)]                                       2
[解説（ステレオ2）]                                       2
[シネテープ/モノラル]                                      2
[ステレオ放送, 副音声による解説放送（第1 - 5作）]                     2
[ステレオ放送・解説放送（ステレオ2）]                              1
[ステレオ放送, ステレオ2音声（2020）, 副音声による解説放送（2020）]         1
[ステレオ放送, ステレオ2音声（第2シリーズ）, 副音声による解説放送（スペシャル）]      1
[解説放送（ステレオ2）]                                     1
[ステレオ放送, 解説放送（ステレオ2）]                             1
[解説放送[5]]                                         1
[ステレオ放送, 一部の回で音声多重放送を実施]                          1
[鈴木昭彦]                                            1
[レギュラー放送, モノステレオ放送→モノラル放送, 不定期放送, ステレオ放送]         1
[解説放送（単発ドラマ）, ステレオ放送（連続ドラマ）]                      1
[ステレオ放送, 副音声放送(最終回のみ)]                            1
[解説放送[6]]                                         1
[第1期：モノラル放送, 第2期：ステレオ放送]                          1
[ステレオ放送, 副音声放送[注 1]]                              1
[解説放送（MBS・TBSのみ）]                                 1
[ステレオ放送, 解説放送（ステレオ2）（第2シリーズ）]                     1
[解説放送（単発版）, ステレオ放送（連続ドラマ）]                        1
Name: 音声形式, dtype: int64
放送国・地域 value counts = [日本]                                                             1014
[韓国]                                                                3
[イギリス]                                                              2
[台湾]                                                                1
[JPN]                                                               1
[韓国、日本]                                                             1
[【本放送】, 日本, 【同日・同時刻放送】, カンボジア, 香港, インドネシア, フィリピン, シンガポール, タイ]       1
Name: 放送国・地域, dtype: int64
放送時間 value counts = [日曜22:00 - 22:49]                                                                        23
[木曜 21:00 - 21:54]                                                                       21
[日曜 21:00 - 21:54]                                                                       19
[同上]                                                                                     18
[日曜 22:30 - 23:25]                                                                       18
                                                                                         ..
[水曜2:40 - 3:10, （火曜日深夜）]                                                                  1
[金曜日 19:00 - 22:52（232分）, 金曜日 18:00 - 22:52（292分）, 土曜日19:00 - 23:10（250分）]                1
[【毎日放送・制作局】, 月曜 0:50 - 1:20（日曜深夜）, 【TBS】, 水曜 1:28 - 1:58（火曜深夜、TBS）]                       1
[21:00 - 22:51]                                                                           1
[月曜日 - 土曜日, 12:45 - 13:00（総合）, 23:00 - 23:15（BSプレミアム）, 土曜 9:30 - 11:00（1週間分 BSプレミアム）]     1
Name: 放送時間, Length: 360, dtype: int64
放送期間 value counts = [2020年10月14日-2021年3月17日]                       14
[2015年1月18日]                                   13
[2019年4月8日-2020年3月27日]                          6
[2021年4月8日-6月17日]                               5
[2021年4月30日-7月2日]                               5
                                               ..
[2018年7月19日-9月20日]                              1
[2016年10月3日-2017年3月25日]                         1
[2018年7月27日 (26日深夜) - 10月12日 (11日深夜)（全12話）]     1
[2021年1月9日-2月13日]                               1
[2017年4月11日-6月13日]                              1
Name: 放送期間, Length: 799, dtype: int64
放送分 value counts = [54分]                 286
[30分]                 154
[60分]                  93
[55分]                  69
[49分]                  51
                     ...
[140分]                  1
[前編 138分, 後編 133分]      1
[118分]                  1
[70[3]分]                1
[71分]                   1
Name: 放送分, Length: 65, dtype: int64
回数 value counts = [10]          216
[8]           116
[1]            88
[9]            65
[12]           61
             ...
[全6話+外伝2話]      1
[40]            1
[64]            1
[5（予定）]         1
[6[注 1]]        1
Name: 回数, Length: 79, dtype: int64
演出 value counts = [渡邊良雄ほか]                                                     4
[常廣丈太（テレビ朝日）, 本橋圭太（アズバーズ）, 山本大輔（S3）]                         4
[木村隆文, 吉川邦夫, 田中正, 小林大児, 土井祥平, 渡辺哲也, 保坂慶太]                    4
[井上剛, 西村武五郎, 一木正恵, 大根仁, 桑野智宏, 林啓史, 津田温子, 松木健祐, 渡辺直樹, 北野隆]    4
[渡辺一貴, 福井充広, 藤並英樹, 深川貴志, 村橋直樹, 安藤大佑]                         4
                                                            ..
[武内英樹, 石川淳一, 洞功二]                                            1
[秋山純, 落合正幸, 常廣丈太]                                            1
[狩山俊輔, 水野格, 茂山佳則]                                            1
[松山博昭, 宮木正悟, 関野宗紀, 品田俊介, 小原一隆]                               1
[石塚嘉, 松園武大, 宇佐川隆史]                                           1
Name: 演出, Length: 537, dtype: int64
放送枠 value counts = [プレミアムドラマ]           41
[大河ドラマ]              32
[ドラマ10]              31
[ドラマ24]              30
[火曜ドラマ]              29
                     ..
[土曜プレミアム（前編）]         1
[水曜ミステリー9]            1
[TBS水曜10時枠の連続ドラマ]     1
[NHK夜の連続ドラマ]          1
[プラチナイト・木曜ドラマ]        1
Name: 放送枠, Length: 134, dtype: int64
ナレーター value counts = [近藤サト]                   5
[三宅健太]                   5
[植草朋樹（テレビ東京）]            5
[池田秀一]                   4
[ビートたけし（噺） /森山未來（語り）]    4
                        ..
[ましゅるむ（予告編)]             1
[池田昌子]                   1
[井上和彦]                   1
[柴田恭兵（語り）]               1
[高木渉]                    1
Name: ナレーター, Length: 118, dtype: int64
製作総指揮 value counts = [内山聖子（ゼネラルプロデューサー）]                        7
[菓子浩（制作統括）, 福岡利武（制作統括）]                    4
[屋敷陽太郎（制作統括）, 吉川邦夫（制作統括）]                  4
[内山聖子（テレビ朝日、GP）]                           4
[内山聖子（テレビ朝日）]                              4
                                          ..
[土屋勝裕（NHK編成局コンテンツ開発センター）, 池田健司（アックスオン）]    1
[三鬼一希（制作統括）]                               1
[中川順平（CP、テレビ東京）]                           1
[前西和成（CP・読売テレビ）]                           1
[（チーフプロデューサー）, 矢口久雄, 貴島誠一郎]                1
Name: 製作総指揮, Length: 119, dtype: int64
映像形式 value counts = [文字多重放送]                                       107
[文字多重放送, 番組連動データ放送]                             94
[16:9]                                           6
[文字多重放送（S2 - ）, 番組連動データ放送（2017・2019年大晦日SP）]      5
[文字多重放送, 連動データ放送]                                4
[音声多重放送]                                         3